### ISSUE TITLE
Bone Image Upload UI

### ISSUE THREAD

**Issue by DeviPriya-Kolla** [oss-slu/DigitalBonesBox#13]
- **Description:**
Create a user interface (UI) for uploading images of a single bone. This UI will allow users to load bone images into the editor for annotation.

- **Acceptance Criteria:**
User can upload an image of a single bone through the UI.
Uploaded bone image is displayed in the editor.
Image should have a resolution limit (e.g., 10MB) to avoid performance issues.
If no image is uploaded, the user should see a placeholder or a prompt to upload an image.

- **Why It's Useful:** 
This is the basic setup that allows users to start interacting with the editor by uploading bone images for annotation. It’s the foundation of the entire bone editing tool.

- **Steps to Resolve:**
1. Design a simple UI layout with an "Upload Image" button.
2. Implement the file picker for image upload.
3. Display the uploaded image inside the bone editor canvas.
4. Handle cases of incorrect file formats or sizes, providing appropriate feedback to the user.
5. Test UI with different image sizes and formats (e.g., PNG, JPEG).

**Comment by SowmyaKoneti** [comment]
I will work on this
